server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: "jdbc:mariadb://127.0.0.1/karim"
    username: "karim"
    password: "karim"
    driver-class-name: "org.mariadb.jdbc.Driver"
  cache:
    jcache:
      config:
        classpath: "ehcache.xml"

#spring:
#  datasource:
#    url: "jdbc:mariadb://192.168.124.238:1322/dfinder"
#    username: "dfinder"
#    password: "1q2w3e4r5T#"
#    driver-class-name: "org.mariadb.jdbc.Driver"

mybatis:
  # mapper 경로 지정
  mapper-locations: query/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

vault.props:
  schema: http
  host: 192.168.124.238
  port: 8200
  roleId: 5b08421f-7f60-d528-dabb-1da487bbac08
  secretId: ea01eddd-d199-461b-58f1-ba06957cc189
  mainPath: fds
  subPath: db_atomysql