server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: "jdbc:mariadb://127.0.0.1/karim"
    username: "karim"
    password: "karim"
    driver-class-name: "org.mariadb.jdbc.Driver"
  cache:
    cache:
      config: classpath:ehcache.xml

mybatis:
  # mapper 경로 지정
  mapper-locations: query/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

vault.props:
  schema: http
  host: 127.0.0.1
  port: 8200
  roleId: 5b08421f-7f60-d528-dabb-1da487bbac08
  secretId: ea01eddd-d199-461b-58f1-ba06957cc189
  mainPath: fds
  subPath: db_atomysql